name: Update age

on:
    schedule:
        - cron: "0 0 1 1 *" # Run once a year on Jan 1st
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Update README.md with new age
              run: |
                  YEAR=$(( ($(date +%s) - $(date -d "2002-11-13" +%s)) / 31536000 ))
                  sed "s/{{ YEAR }}/$YEAR/g" README.original > README.md

                  if git diff --quiet README.md; then
                    echo "No changes, age is up-to-date."
                    exit 0
                  fi

                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add README.md
                  git commit -m "Update age in README"
                  git push
