name: Update Age in README

on:
    schedule:
        - cron: "0 0 * * *" # every day at midnight UTC
    workflow_dispatch: # manual trigger

jobs:
    update-age:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Run age update script
              run: |
                  npm install fs
                  node .github/scripts/updater.js

            - name: Commit changes
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'
                  git add README.md
                  git commit -m "chore: update age in README" || echo "No changes to commit"
                  git push
