name: Update Age
on:
    schedule:
        - cron: "0 0 * * *" # Updates daily
    workflow_dispatch:
jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Update age in README
              run: |
                  cp README.md README.original
                  YEAR=$(( ($(date +%s) - $(date -d "2002-11-13" +%s)) / 31536000 ))
                  sed "s/{{ YEAR }}/$YEAR/g" README.original > README.md
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add README.md
                  git commit -m "up"
                  git push
